### ISSUE TITLE
dlopen failed: cannot locate symbol "rust_eh_personality" referenced by libirondash_engine_context_native.so

### ISSUE THREAD

**Issue by duowanSir** [irondash/irondash#56]
I hava a flutter project，in it I use some flutter lib and it's dependency tree like below
```
├── super_clipboard 0.6.4
│   ├── super_native_extensions 0.6.4
│   │   ├── irondash_engine_context 0.3.1
│   │   │   ├── flutter...
│   │   │   └── plugin_platform_interface...
│   │   ├── irondash_message_channel 0.3.1
│   │   │   ├── ffi...
│   │   │   └── flutter...
│   │   ├── pixel_snap 0.1.5
│   │   │   └── flutter...
│   │   ├── collection...
│   │   ├── device_info_plus...
│   │   ├── ffi...
│   │   ├── flutter...
│   │   ├── flutter_web_plugins...
│   │   ├── js...
│   │   ├── meta...
│   │   ├── path...
│   │   └── uuid...
│   ├── collection...
│   ├── flutter...
│   └── meta...
```
On Android platform，when IrondashEngineContextPlugin was register，exception happend
```
Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "rust_eh_personality" referenced by /lib/arm64/libirondash_engine_context_native.so
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1657)
                                                                                                    	at dev.irondash.engine_context.IrondashEngineContextPlugin.<clinit>(IrondashEngineContextPlugin.java:153)
                                                                                                    	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:99)
```
Then I use nm to see the symbol in apk lib

```
 ➜  arm64-v8a nm -D libirondash_engine_context_native.so 
                 U ALooper_forThread
0000000000001b70 T JNI_OnLoad
                 U __cxa_atexit
                 U __cxa_finalize
                 U __register_atfork
0000000000001d74 T irondash_engine_context_get_class_loader
0000000000001d68 T irondash_engine_context_get_java_vm
0000000000001d80 T irondash_engine_context_get_main_looper
                 U rust_eh_personality 
```                                                           
rust_eh_personality symbol is undefined，but why？and how to resolve it

**Comment by duowanSir** [comment]
Looking forward to your reply, thanks very much

**Comment by knopp** [comment]
You are using a very old version of super_clipboard.

**Comment by duowanSir** [comment]
Thanks，I will try a new version today.But I'm curious, is this a known issue?
rust_eh_personality is in the core lib，so this issue happened on no_std compile？

**Comment by duowanSir** [comment]
I upgrade to 0.8.17 then bug disappeared
